### PR TITLE
Reformat 2-space JSONs to use tabs.

### PR DESCRIPTION
**Pull request by vini2003**

### CODE REVIEW

**Comment by vini2003** [comment]
The commit history is weird but the content is correct.

**Comment by vini2003** [comment]
Do not merge yet, investigating more inconsistencies. Damn, guys.

**Comment by Shrimpstress** [comment]
Could I have a little clarification on why this is necessary? Both tabs and 4 spaces are acceptable in the Fabric Community Style Guidelines.

**Comment by vini2003** [comment]
Some JSONs are using 2 spaces @Zundrel

**Comment by Shrimpstress** [comment]
Alright, that makes a lot of sense then. I'll look at this PR once you have it ready.

**Review by Shrimpstress — APPROVED** [review]
After a slightly lengthy review everything looks fine to me.

**Comment by vini2003** [comment]
Shit's fucked.

**Pull request closed without merging**
