### PR TITLE
Config

### PR DESCRIPTION
**Pull request by GiantNuker**
At least I think thats whats in here

### CODE REVIEW

**Comment by GiantNuker** [comment]
uh oh this dosent look right

**Comment by GiantNuker** [comment]
nope its broken

**Comment by GiantNuker** [comment]
dont merge this

**Comment by Draylar** [comment]
ok merged

**Review by Shrimpstress — APPROVED** [review]
Looks great to me.

**Review by Draylar — APPROVED** [review]

**Comment by basisbit** [comment]
fyi, this thread was mentioned at [reddit](https://www.reddit.com/r/ProgrammerHumor/comments/dcd90h/a_tragic_tale_told_in_four_messages/ ) and various other places. ^^

**Comment by Draylar** [comment]
im famous

**Pull request merged**
