### PR TITLE
Spanish translation updates

### PR DESCRIPTION
**Pull request by emilyploszaj**
Updated the Spanish translations to be up to date with current en_us translations.
Also added myself to the list of authors a bit late.

### CODE REVIEW

**Review by Shnupbups — APPROVED** [review]

**Review by YanisBft — APPROVED** [review]

**Review by Shrimpstress — APPROVED** [review]

**Review by Juuxel — CHANGES_REQUESTED** [review]
Could you reindent `es_es.json` with tabs? Some lines have spaces and some have tabs.

**Review by vini2003 — CHANGES_REQUESTED** [review]
Reformat files to use 4-spaches or a tab.

**Comment by emilyploszaj** [comment]
Inconsistent indentation fixed

**Review by vini2003 — APPROVED** [review]
4 spaces now, seems fine.

**Pull request merged**
