### PR TITLE
Spider Lair feature

### PR DESCRIPTION
**Pull request by YanisBft**
Spider lairs consist of a spider spawner with randomly generated cobwebs around it. They appear with a chance of 300, like witch wells.

Possible idea list (send feedback and help):
- [x] A loot chest

### CODE REVIEW

**Comment by Shnupbups** [comment]
I like the idea of making our own variant on a Spider. Maybe it could do more damage than a standard spider, and inflict poison like a cave spider?

**Comment by Shrimpstress** [comment]
Maybe some type of Demonic Spider which hides its appearance as a normal spider until you attack it. It then suddenly sheds its skin and looks a lot more demonic, also dealing more damage.

**Comment by valoeghese** [comment]
I notice you haven’t merged the master upstream branch containing barrows :thinking:

**Comment by Draylar** [comment]
Maybe the pit should be down inside the ground, as opposed to being above ground?

I'm envisioning a small pit with walls made of a mix of cobblestone and stone. The spider spawners are at the bottom (and one or two in the center) and are covered by webs. The pit would be from 5-10 blocks deep, and a chest could be next to the spawner in the center of the pit. 

This would mostly reduce the clutter of having giant wads of webs above ground. You _could_ (this is evil) also have a hidden trap block so players fall into the spider pits.

**Comment by YanisBft** [comment]
I like your idea of a demonic spider @Zundrel :) I'm bad at textures though so you could make this change after this PR ^^

@Draylar will look into that, I may have an idea of a hidden trap block hehe

**Comment by Draylar** [comment]
Here's a 15-second mockup I did of an underground version:

image

The inside would look something like this:
image

The mass fill of cobwebs wouldn't be fun if there was a trapped floor involved, but you get the general idea. Maybe it could also lead to a spider cave underground? :eyes:

**Comment by YanisBft** [comment]
@Draylar I will let you do the underground stuff if you don't mind ^^

**Comment by Draylar** [comment]
Sounds good!

**Pull request merged**
