### PR TITLE
small things

### PR DESCRIPTION
**Pull request by Shnupbups**
- fixed Hallowed Ingot texture being 16x17
- changed Reaper's Scythe texture to match Hallowed Metal
- Witch Water no longer gives the potion effects to Witches
- Witch Water's potion effects now last for 5 seconds instead of 1 because 1 second blindness was a legitimate epilepsy risk
- added (currently unused) Ogre texture
- added 3 (also currently unused) structures (Crypt, Cultist Church, House) to the data folder

### CODE REVIEW

**Comment by vini2003** [comment]
I'm not entirely sure how I managed to make 16x17 textures.

**Comment by Shnupbups** [comment]
well i mean the originals were animated with multiple frames, which means they were taller than 16x16, so when cropping them you just accidentally left an extra pixel of height in

**Comment by vini2003** [comment]
Ah yeah that makes sense. Thanks for the fixes.

**Review by vini2003 — APPROVED** [review]

**Review by Shrimpstress — APPROVED** [review]
I actually looked at it earlier this morning but forgot to approve.

**Review by Juuxel — APPROVED** [review]

**Pull request merged**
