### PR TITLE
Renamed everything to The Hallow

### PR DESCRIPTION
**Pull request by Shnupbups**
but this time I did it mwahahaha

OwO who dis

### CODE REVIEW

**Comment by vini2003** [comment]
noh

**Comment by Shnupbups** [comment]
mine is better because it has no merge conflicts

**Comment by Shnupbups** [comment]
get rekt

**Comment by vini2003** [comment]
hipitty hoppity your opinion is invalid

**Comment by vini2003** [comment]
Mine has a large amount of extra fixes and updates that would break entirely if yours was merged. Please honestly, just wait a few hours.

**Comment by vini2003** [comment]
I sincerely don't care anymore. Feel free to.

**Pull request closed without merging**
