### PR TITLE
Add Brown Bag item

### PR DESCRIPTION
**Pull request by Draylar**
Introducing the Brown Bag: your budget introduction to Halloween costumes! Designed by a professional costume creator, this mask is the _perfect_ fit for your head. Not only does it act as a stylish hat, but it also prevents mobs from getting mad at you. Who would want to fight someone with a brown bag on their head? 

_Name up for discussion. It was originally called the spooky mask, not sure which one I'll stick with._

**Features:**
  - mask implemented with Trinkets API
  - enderman won't aggro on you when you wear it
  - eyes are fitted perfectly; no overlay like pumpkins!

**To-do:**
  - recipe
  - clean up PR
  - get an actual texture to use (do not look at what I'm currently using)
  - add durability
  - fix tooltip

### CODE REVIEW

**Comment by Shnupbups** [comment]
1. rename it to paper bag
2. make its recipe a helmet but with paper
3. fix the conflicts
4. add it as a valid trick or treating costume piece

**Comment by Draylar** [comment]
Messed up my merge somehow, will fix tonight.

**Comment by valoeghese** [comment]
5 merge conflicts wow

**Comment by GiantNuker** [comment]
Ikr

**Comment by Draylar** [comment]
Going to re-try this later.

**Pull request closed without merging**
