### PR TITLE
Make the dimension textures spookier as well as fix up server compat.

### PR DESCRIPTION
**Pull request by Shrimpstress**
I just made the grass textures darker and less saturated to fit with the theme of the dimension better.

In addition I've made multiple methods client-side to help fix server compat, but currently the dimension is not registered on the server for some reason which is why I have made this PR a Draft for now. Once server compat is fixed, this PR can be accepted.

### CODE REVIEW

**Comment by Shrimpstress** [comment]
I've completely fixed server compat with the mod by not registering our custom ChunkGeneratorType. I'm not sure why vanilla registers these as they don't seem to have to be synced for proper functionality, as well as actually sync improperly for custom ChunkGeneratorTypes.

**Comment by Shrimpstress** [comment]
I also just added World Traveler JiJ so that building and using the mod will be slightly easier without you having to manually build World Traveler.

**Comment by Shrimpstress** [comment]
Scratch that, server compat still broken. Don't merge.

**Comment by Shrimpstress** [comment]
And we're good now.

**Review by Shnupbups — CHANGES_REQUESTED** [review]
I like the original brighter leaves texture better, it was a nice contrast IMO. If you're gonna change it, at least change the sapling too.
Other than that, is good.

**Comment by Shrimpstress** [comment]
Alright I've reverted back to the original Deadwood Leaves texture.

**Review by Shnupbups — APPROVED** [review]

**Review by ImAK9 — APPROVED** [review]

**Pull request merged**
